### ISSUE TITLE
Vision-Language paper that adapts CLIP to challenging tasks by utilizing SSL

### ISSUE THREAD

**Issue by omipan** [fawazsammani/awesome-vision-language-pretraining#1]
- **[SVL-Adapter]** SVL-Adapter: Self-Supervised Adapter for Vision-Language Pretrained Models [[pdf]](https://arxiv.org/pdf/2210.03794.pdf) [[code]](https://github.com/omipan/svl_adapter)

**Comment by omipan** [comment]
- **[SVL-Adapter]** SVL-Adapter: Self-Supervised Adapter for Vision-Language Pretrained Models [[pdf]](https://arxiv.org/pdf/2210.03794.pdf) [[code]](https://github.com/omipan/svl_adapter)

**Comment by fawazsammani** [comment]
Thanks. Will add it today
